@startuml
'https://plantuml.com/sequence-diagram

participant "Utilisateur" as user
participant "bouton : Button" as Button
participant "controleur : ControleurAjoutColonne" as controleur
participant "m : Modele" as m

title Appuie sur le bouton d'ajout de colonne par l'utilisateur

activate user
user -> Button : clic
activate Button
Button -> controleur : handle(eventAction)
activate controleur
controleur -> m : ajouterColonne("Nouvelle colonne")
activate m
m--> controleur
deactivate m
controleur --> Button
deactivate controleur
Button --> user
deactivate Button




@enduml