@startuml
'https://plantuml.com/sequence-diagram

actor user
participant "controleurAjoutCol : ControleurAjouterColonne" as CC
participant "m : Modele" as m

activate user
user -> CC : clic
activate CC
user -> m : ajouterColonne("Nouvelle colonne")
activate m
alt !isBlank("Nouvelle colonne")
    create "colonne : Colonne" as c
    m -> c : new
else isBlank("Nouvelle colonne")
end

m --> CC
deactivate m
CC--> user
deactivate CC




@enduml