@startuml

title "Affichage de l'application en vue Bureau (lors du lancement de l'application)"
participant TestVue
participant Modele as "model : Modele"
participant VueAccueil as "vue : VueAccueil"
participant VueBureau as "modeAffichage : VueBureau"


create Modele
TestVue -> Modele : new Modele()
create VueAccueil
TestVue -> VueAccueil : new VueAccueil(model)

VueAccueil -> VueBureau : getInstance()
activate VueBureau
VueBureau --> VueAccueil : modeAffichage [VueBureau]
deactivate VueBureau

TestVue -> Modele : ajouterObservateur(vue)
activate Modele
Modele --> TestVue
deactivate Modele
TestVue -> VueAccueil : actualiser()
activate VueAccueil
VueAccueil -> VueBureau : genererAffichage()
activate VueBureau
VueBureau --> VueAccueil : this [Pane]
VueAccueil --> TestVue









@enduml