@startuml

class Repository{
    - static String nomFichierSauvegarde
    - ObjectInputStream inputStream
    - ObjectOutputStream outputStream
    - Repository instance
    - Repository()
    + static getInstance() : Repository
    + closeConnexion()
}

@enduml