@startuml

class Repository{
    - static String nomFichierSauvegarde
    - ObjectInputStream inputStream
    - ObjectOutputStream outputStream
    - static Repository instance
    - Repository()
    + static getInstance() : Repository
}

@enduml