@startuml

actor "Utilisateur" as User
participant "VueAccueil" as V
participant "PopupArchive" as P
participant "Modele" as M
participant "Archive" as A

title Séquence : Afficher archive

User -> V : Clique sur le bouton "Archive"
activate V

V -> V : afficherArchive(tache)

V -> P : display(model)
activate P

P -> M : getArchive()
M --> P : archive
activate M
P -> A : getTaches()
activate A
A --> P : List<Tache>
Note right of P : Creation affichage

User -> P : Clique droit sur la tache et clique sur Supprimer
P -> M : supprimerArchiverTache(tache)

opt contains(tache)
    M -> A : supprimerTache(tache);
    A --> M
    deactivate A
    M -> M : notifier();
end

P -> table : getItems().remove(tache)
activate table
table --> P
deactivate table
Note right of P : Mettre a' jour affichage

User -> P : Clique sur le bouton "Exit"
P -> P : window.close()
P --> User : Retour au contrôle de l'UI
deactivate P

@enduml
